### ISSUE TITLE
Download Original not work in https://mobile.twitter.com 

### ISSUE THREAD

**Issue by SyaoranChang** [euank/twitter-image-helper#10]
Hi,

Firefox 63.01
twitter-image-helper 0.6.0

Download Original not work in https://mobile.twitter.com

**Comment by euank** [comment]
Thanks for the report. This extension was made for use on https://twitter.com and I'm not surprised it doesn't work on https://mobile.twitter.com.

I'll leave this open as a feature request for it to work on the mobile site too, and might get to implementing it at some point as well.

**Comment by euank** [comment]
I've released v0.7.0 of the extension. It should work now.

Thanks for the report!
