### ISSUE TITLE
New download picture feature, not adhearing to browser defaults

### ISSUE THREAD

**Issue by kazie** [euank/twitter-image-helper#6]
Hello!

I really like the new feature where one can download the picture directly instead of having to do "Save As..." from the opened tab.

Sadly I download pictures to different folders depending on content, and I would not like to manually browse the file and move them once they are downloaded.

Reading the documentation it would be an easy fix to make it choose the browsers default behaviour instead of enforcing download to the default folder.

My settings are as following:
![2018-07-08-102755_682x160_scrot](https://user-images.githubusercontent.com/1390887/42418140-8dd72942-829a-11e8-9613-95a3fac2fdac.png)

And [according to the documentation](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/downloads/download):
![2018-07-08-103054_685x219_scrot](https://user-images.githubusercontent.com/1390887/42418151-baa47b0a-829a-11e8-970c-1e3af63c11ce.png)

If the "saveAs" field would have been left `undefined` instead of `false` then it would listen to ones browsers settings instead! (Mine as you can see is default to "saveAs").

That is the codechange would need to be in `background.js` more specifically:
```diff
case "twitter-img-download":
   var downloading = browser.downloads.download({
     url: lastOrigUrl,
-    saveAs: false,
     filename: fileName // Optional
   });
   downloading.then(function(id) {/* console.log('triggering download: ', lastOrigUrl, fileName, id);*/}, onError);
   break;
```

Love your plugin, and I would be happy if you could consider this change. :)

**Comment by euank** [comment]
Fixed in #7. Thanks again for the detailed report and fix :+1: 

This should be fixed in v0.6.0, released sometime later today.
