### ISSUE TITLE
Latest version(0.60) Seems to have broken 'open in tab'

### ISSUE THREAD

**Issue by Niftator** [euank/twitter-image-helper#9]
Since updating from 0.4 to 0.6 yesterday I can no longer open images in a new tab. Since opening in current tab means scrolling through twitter again to find my place after going back, and download dumps it in my downloads folder as another mentioned. I did a quick test and it DOES work in 0.5. No big deal, 0.4 works fine still

**Comment by euank** [comment]
The change on 0.6 which is likely relevant is the inclusion of the tab "opener" id ([commit](https://github.com/euank/twitter-image-helper/commit/138a4e42556038add2692b8a453a2c229b779944)).

Support for setting an opener tab was added in Firefox 57. Are you on at least that version?

If that's not it, can you see if there's an obvious error logged to the browser console ('Tools -> Web Developer -> Browser Console'; note that it's different from the more common "Web Console")?

**Comment by euank** [comment]
I'm closing this due to lack of response; I'll assume it's just an old version of firefox to blame unless I hear otherwise.
